apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: c8s-public
  namespace: c8s
spec:
  gateways:
  - knative-serving/knative-ingress-gateway
  hosts:
  - c8s.example.com
  - "*.c8s.example.com"
  http:
  - retries:
      attempts: 3
      perTryTimeout: 10m0s
    route:
    - destination:
        host: c8s-service.c8s.svc.cluster.local
        port:
          number: 80
      headers:
        request:
          add:
            Knative-Serving-Namespace: c8s
            Knative-Serving-Revision: c8s-service
      weight: 100
    timeout: 10m0s
