apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: c8s-certificate
  namespace: istio-system
spec:
  secretName: istio-ingressgateway-certs
  issuerRef:
    name: issuer-letsencrypt
    namespace: istio-system
  commonName: c8s.example.com
  dnsNames:
  - c8s.example.com
  - "*.c8s.example.com"
  acme:
    config:
    - dns01:
        provider: acmedns
      domains:
        - c8s.example.com
        - "*.c8s.example.com"
